@url = http://192.168.18.100:8000/api
# @url = https://mobile-customer.dotsco.re/api
@token = 97|2Le6WgR1Momk18yYuBEKAHlBeqUXCW30U7hNaNVT5c667c65
### ===
POST {{url}}/login
Content-Type: application/json
 
{
    "username" : "user",
    "password" : "password123",
    "tenantID" : "ksp_mrn",
    "clientType" : "CUSTOMER"
}

### ===
POST {{url}}/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "old_password" : "password123",
    "new_password" : "password123!"
}

### ===
GET {{url}}/tenants
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
POST {{url}}/create-reservation
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "destinationService" : "001",
    "reason" : "Menjenguk",
    "branchId" : "001",
    "attendAtStart" : "2023-09-18 12:00:00.048+07",
    "attendAtEnd" : "2023-09-18 15:00:00.048+07",
    "time" : "0100-1900"
}

###
GET {{url}}/reservation/1697548721385241143
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/office
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/saving
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/saving/product-type
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/saving/00102020000009
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/saving/history/00102010000572
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
POST {{url}}/saving
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productType" : "02",
    "currentBalance" : "230000"
}

### ===
POST {{url}}/saving/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "savingId" : "0980980879987",
    "amount" : "1000000",
    "paymentMethodId" : "00105000000476",
    "recipient" : "Namaaaa"
}

### ===
GET {{url}}/loan
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/loan/00104010000459
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/loan/product-type
Content-Type: application/json
Authorization: Bearer {{token}}

### === Belakang
GET {{url}}/loan/bill/00104010001239
Content-Type: application/json
Authorization: Bearer {{token}}

### === Depan
GET {{url}}/loan/now/00104010001239
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
POST {{url}}/loan
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productType" : "02",
    "currentBalance" : "200000",
    "period" : "4"
}

### ===
POST {{url}}/loan/repay
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "loanId" : "0980980879987",
    "amount" : "1000000",
    "paymentMethodId" : "01299",
    "recipient" : "DANA"
}

### 
POST {{url}}/loan/topup
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "loanId" : "0980980879987",
    "amount" : "1000000",
    "reason" : "Halooo"
}

### ===
GET {{url}}/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/deposit/00103120000050
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/deposit/product-type
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
POST {{url}}/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productType" : "03",
    "currentBalance" : "200000"
}

GET {{url}}/notification
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/notification/1699001478869365151
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET {{url}}/image
Content-Type: application/json
Authorization: Bearer {{token}}

### ===
GET http://192.168.18.100:8000/images/2023-10-18_051920_BPR_Kreasi_Nusantara_Dev.jpeg

### ===
GET {{url}}/payment-method/1/00102010000456
Content-Type: application/json
Authorization: Bearer {{token}}
# loan : 00104010000867
# saving : 00102010000456

### ===
GET {{url}}/tenant/900001

### ===
GET {{url}}/hehe

### ===
POST {{url}}/create
Content-Type: application/json

{
    "data": [
    {
        "public_id": "5",
        "name": "BPR Sukma",
        "username": "sukmajaya",
        "token": "",
        "Kode AO": "1",
        "database": "ksp_sinarmas_kalimantan",
        "pwd1": "sukmajaya",
        "pwd2": "$2y$04$PnE4zyW0AoIy\/0xqWoDF7.IZM.SLcysLKi7szJaMOzg68n6\/JPN4q"
    }
]
}

### 
GET {{url}}/check-token
Content-Type: application/json

### ===
GET {{url}}/topup-reason